import { NextRequest, NextResponse } from 'next/server'
import { Resend } from 'resend'

const resend = new Resend(process.env.RESEND_API_KEY)

export async function POST(request: NextRequest) {
  try {
    const { email, brdContent, fileName } = await request.json()

    if (!email || !brdContent) {
      return NextResponse.json({ error: 'Email and BRD content are required' }, { status: 400 })
    }

    console.log(' Sending email to:', email)

    // Send email with BRD content
    const { data, error } = await resend.emails.send({
      from: 'AI BRD Generator <onboarding@resend.dev>',
      to: email,
      subject: `Your BRD Document - ${fileName || 'Generated BRD'}`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
          <h1 style="color: #7c3aed; border-bottom: 3px solid #7c3aed; padding-bottom: 10px;">
            Your Business Requirements Document
          </h1>
          
          <p style="font-size: 16px; color: #333; line-height: 1.6;">
            Your AI-generated Business Requirements Document is ready. Please find the content below:
          </p>
          
          <div style="background-color: #f9fafb; border: 1px solid #e5e7eb; border-radius: 8px; padding: 20px; margin: 20px 0;">
            <pre style="white-space: pre-wrap; font-family: 'Courier New', monospace; font-size: 12px; color: #374151; line-height: 1.5;">${brdContent}</pre>
          </div>
          
          <p style="font-size: 14px; color: #6b7280; margin-top: 30px;">
            You can also download this document in PDF or DOCX format from the application.
          </p>
          
          <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 30px 0;" />
          
          <p style="font-size: 12px; color: #9ca3af; text-align: center;">
            Generated by AI BRD Generator | Powered by AI
          </p>
        </div>
      `,
    })

    if (error) {
      console.error(' Email send error:', error)
      return NextResponse.json({ error: 'Failed to send email' }, { status: 500 })
    }

    console.log(' Email sent successfully:', data)

    return NextResponse.json({
      success: true,
      message: 'Email sent successfully',
      emailId: data?.id,
    })
  } catch (error) {
    console.error(' Email error:', error)
    return NextResponse.json(
      { error: error instanceof Error ? error.message : 'Failed to send email' },
      { status: 500 }
    )
  }
}
